/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop.lab.todoornottodo;

import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author Neon
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    
    public GUI() {
        //public GUI(JList<Task> taskList) {
        //this.taskList = taskList;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addTaskFrame = new javax.swing.JFrame();
        bottomPanel1 = new javax.swing.JPanel();
        addTaskOkButton = new javax.swing.JButton();
        addTaskCancelButton = new javax.swing.JButton();
        TopPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        addTitleTextField = new javax.swing.JTextField();
        addDateTextField = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        addDescriptionTextArea = new javax.swing.JTextArea();
        editTaskFrame = new javax.swing.JFrame();
        bottomPanel2 = new javax.swing.JPanel();
        editTaskOkButton = new javax.swing.JButton();
        editTaskCancelButton = new javax.swing.JButton();
        TopPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        editTitleTextField = new javax.swing.JTextField();
        editDateTextField = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        editDescriptionTextArea = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        doneCheckBox = new javax.swing.JCheckBox();
        notDoneCheckBox = new javax.swing.JCheckBox();
        bottomPanel = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taskList = new javax.swing.JList<>();
        TopPanel = new javax.swing.JPanel();
        taskNumTextLabel = new javax.swing.JLabel();
        taskCountDisplay = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        titleDisplayLabel = new javax.swing.JLabel();
        dateDisplayLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        progDisplayLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descDisplayTextArea = new javax.swing.JTextArea();

        addTaskFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addTaskFrame.setTitle("Add Task");
        addTaskFrame.setAlwaysOnTop(true);
        addTaskFrame.setMinimumSize(new java.awt.Dimension(560, 400));
        addTaskFrame.setType(java.awt.Window.Type.POPUP);

        bottomPanel1.setBackground(new java.awt.Color(0, 153, 204));

        addTaskOkButton.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        addTaskOkButton.setText("OK");
        addTaskOkButton.setPreferredSize(new java.awt.Dimension(100, 35));
        addTaskOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTaskOkButtonActionPerformed(evt);
            }
        });

        addTaskCancelButton.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        addTaskCancelButton.setText("Cancel");
        addTaskCancelButton.setPreferredSize(new java.awt.Dimension(100, 35));
        addTaskCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTaskCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bottomPanel1Layout = new javax.swing.GroupLayout(bottomPanel1);
        bottomPanel1.setLayout(bottomPanel1Layout);
        bottomPanel1Layout.setHorizontalGroup(
            bottomPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPanel1Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(addTaskOkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addComponent(addTaskCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bottomPanel1Layout.setVerticalGroup(
            bottomPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottomPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(bottomPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTaskOkButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addTaskCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        TopPanel1.setBackground(new java.awt.Color(0, 255, 204));

        javax.swing.GroupLayout TopPanel1Layout = new javax.swing.GroupLayout(TopPanel1);
        TopPanel1.setLayout(TopPanel1Layout);
        TopPanel1Layout.setHorizontalGroup(
            TopPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        TopPanel1Layout.setVerticalGroup(
            TopPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel5.setText("Name         :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel6.setText("Due Date    :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel7.setText("Description :");

        addTitleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTitleTextFieldActionPerformed(evt);
            }
        });

        addDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDateTextFieldActionPerformed(evt);
            }
        });

        addDescriptionTextArea.setColumns(20);
        addDescriptionTextArea.setRows(5);
        jScrollPane3.setViewportView(addDescriptionTextArea);

        javax.swing.GroupLayout addTaskFrameLayout = new javax.swing.GroupLayout(addTaskFrame.getContentPane());
        addTaskFrame.getContentPane().setLayout(addTaskFrameLayout);
        addTaskFrameLayout.setHorizontalGroup(
            addTaskFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bottomPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TopPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(addTaskFrameLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(addTaskFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(38, 38, 38)
                .addGroup(addTaskFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addTitleTextField)
                    .addComponent(addDateTextField)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addTaskFrameLayout.setVerticalGroup(
            addTaskFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addTaskFrameLayout.createSequentialGroup()
                .addComponent(TopPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(addTaskFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(addTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addTaskFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(addDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addTaskFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(bottomPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        editTaskFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        editTaskFrame.setTitle("Add Task");
        editTaskFrame.setAlwaysOnTop(true);
        editTaskFrame.setMaximumSize(new java.awt.Dimension(560, 400));
        editTaskFrame.setMinimumSize(new java.awt.Dimension(560, 400));
        editTaskFrame.setPreferredSize(new java.awt.Dimension(560, 400));

        bottomPanel2.setBackground(new java.awt.Color(0, 153, 204));

        editTaskOkButton.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        editTaskOkButton.setText("OK");
        editTaskOkButton.setPreferredSize(new java.awt.Dimension(100, 35));
        editTaskOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTaskOkButtonActionPerformed(evt);
            }
        });

        editTaskCancelButton.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        editTaskCancelButton.setText("Cancel");
        editTaskCancelButton.setPreferredSize(new java.awt.Dimension(100, 35));
        editTaskCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTaskCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bottomPanel2Layout = new javax.swing.GroupLayout(bottomPanel2);
        bottomPanel2.setLayout(bottomPanel2Layout);
        bottomPanel2Layout.setHorizontalGroup(
            bottomPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPanel2Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(editTaskOkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addComponent(editTaskCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bottomPanel2Layout.setVerticalGroup(
            bottomPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottomPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(bottomPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editTaskOkButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editTaskCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        TopPanel2.setBackground(new java.awt.Color(0, 255, 204));

        javax.swing.GroupLayout TopPanel2Layout = new javax.swing.GroupLayout(TopPanel2);
        TopPanel2.setLayout(TopPanel2Layout);
        TopPanel2Layout.setHorizontalGroup(
            TopPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        TopPanel2Layout.setVerticalGroup(
            TopPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel8.setText("Name         :");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel9.setText("Due Date    :");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel10.setText("Description :");

        editTitleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTitleTextFieldActionPerformed(evt);
            }
        });

        editDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDateTextFieldActionPerformed(evt);
            }
        });

        editDescriptionTextArea.setColumns(20);
        editDescriptionTextArea.setRows(5);
        jScrollPane4.setViewportView(editDescriptionTextArea);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel11.setText("Progress     :");

        doneCheckBox.setText("Done");
        doneCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneCheckBoxActionPerformed(evt);
            }
        });

        notDoneCheckBox.setText("In Progress");
        notDoneCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notDoneCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editTaskFrameLayout = new javax.swing.GroupLayout(editTaskFrame.getContentPane());
        editTaskFrame.getContentPane().setLayout(editTaskFrameLayout);
        editTaskFrameLayout.setHorizontalGroup(
            editTaskFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bottomPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TopPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(editTaskFrameLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(editTaskFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(38, 38, 38)
                .addGroup(editTaskFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editTaskFrameLayout.createSequentialGroup()
                        .addComponent(doneCheckBox)
                        .addGap(42, 42, 42)
                        .addComponent(notDoneCheckBox))
                    .addGroup(editTaskFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(editTitleTextField)
                        .addComponent(editDateTextField)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        editTaskFrameLayout.setVerticalGroup(
            editTaskFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editTaskFrameLayout.createSequentialGroup()
                .addComponent(TopPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(editTaskFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(editTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editTaskFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(editDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editTaskFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(editTaskFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(doneCheckBox)
                    .addComponent(notDoneCheckBox))
                .addGap(18, 18, 18)
                .addComponent(bottomPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        editTaskFrame.getAccessibleContext().setAccessibleName("Edit Task");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ToDo Or Not ToDo");
        setMaximumSize(new java.awt.Dimension(560, 400));
        setMinimumSize(new java.awt.Dimension(560, 400));
        setSize(new java.awt.Dimension(560, 400));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        bottomPanel.setBackground(new java.awt.Color(0, 153, 204));

        addButton.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        addButton.setText("Add Task");
        addButton.setPreferredSize(new java.awt.Dimension(100, 35));
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        editButton.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        editButton.setText("Edit");
        editButton.setPreferredSize(new java.awt.Dimension(100, 35));
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        removeButton.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        removeButton.setText("Remove");
        removeButton.setPreferredSize(new java.awt.Dimension(100, 35));
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPanelLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        bottomPanelLayout.setVerticalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottomPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        taskList.setModel(model);
        //model.addElement(new Task("Apples", "These are fresh apples", LocalDate.now()));
        taskList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taskListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(taskList);

        TopPanel.setBackground(new java.awt.Color(0, 255, 204));

        taskNumTextLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        taskNumTextLabel.setText("Number of Tasks :");

        taskCountDisplay.setPreferredSize(new java.awt.Dimension(100, 16));

        javax.swing.GroupLayout TopPanelLayout = new javax.swing.GroupLayout(TopPanel);
        TopPanel.setLayout(TopPanelLayout);
        TopPanelLayout.setHorizontalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(taskNumTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(taskCountDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TopPanelLayout.setVerticalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taskNumTextLabel)
                    .addComponent(taskCountDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        int numTasks = model.getSize();
        taskCountDisplay.setText(Integer.toString(numTasks));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Name           :");

        titleDisplayLabel.setPreferredSize(new java.awt.Dimension(38, 16));

        dateDisplayLabel.setPreferredSize(new java.awt.Dimension(38, 16));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Due Date    :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Progress      :");

        progDisplayLabel.setPreferredSize(new java.awt.Dimension(38, 16));
        progDisplayLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                progDisplayLabelMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Description :");

        descDisplayTextArea.setEditable(false);
        descDisplayTextArea.setColumns(20);
        descDisplayTextArea.setRows(5);
        jScrollPane2.setViewportView(descDisplayTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(progDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(titleDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(TopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(titleDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(progDisplayLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
            addDescriptionTextArea.setText("");
            addDateTextField.setText("");
           addTitleTextField.setText("");     
            //dateDisplayLabel.setText("");   
        
        addTaskFrame.setVisible(true);
    }//GEN-LAST:event_addButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
         
        
        int selectedIndex = taskList.getSelectedIndex();
    if (selectedIndex == -1) {
        // show error message that no task is selected
        JOptionPane.showMessageDialog(this, "Please select a task to edit.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
        
    }
        
        Task p = taskList.getSelectedValue();
         editTitleTextField.setText(p.getTitle());
         DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");


              //String formattedDate = dueDate.format(formatter);

                //dueDateLabel.setText(formattedDate);
             

         editDateTextField.setText((p.getDueDate()).format( formatter) );
         editDescriptionTextArea.setText(p.getDescription());
         editTaskFrame.setVisible(true);
    }//GEN-LAST:event_editButtonActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        
    }//GEN-LAST:event_formMouseClicked

    private void taskListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taskListMouseClicked
         Task p = taskList.getSelectedValue();
         titleDisplayLabel.setText(p.getTitle());
         dateDisplayLabel.setText((p.getDueDate()).format(DateTimeFormatter.ISO_DATE) );
         descDisplayTextArea.setText(p.getDescription());
         
          if (p.isDone()) {
                progDisplayLabel.setText("Completed");
          } else {
                progDisplayLabel.setText("In Progress");
            }

         jLabel1.setVisible(true);
         jLabel2.setVisible(true);
         jLabel3.setVisible(true);
         jLabel4.setVisible(true);
         descDisplayTextArea.setVisible(true);
    }//GEN-LAST:event_taskListMouseClicked

    private void progDisplayLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progDisplayLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_progDisplayLabelMouseClicked

    private void addTaskOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTaskOkButtonActionPerformed
                                    
        
                String title = addTitleTextField.getText();
                if (title.isEmpty()) {
                        JOptionPane.showMessageDialog(null, "Please enter a title for the task.");
                         return; // exit the method
                 }
        
                
                
                String description = addDescriptionTextArea.getText();
                if (addDateTextField.getText().isEmpty()) {
                        JOptionPane.showMessageDialog(addTaskFrame, "Due date cannot be empty", "Error", JOptionPane.ERROR_MESSAGE);
                        return;
                   }
                
                
                LocalDate dueDate;
                
                 //DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
               // LocalDate dueDate = LocalDate.parse(addDateTextField.getText(), formatter);
        try {
            dueDate = LocalDate.parse(addDateTextField.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        } catch (DateTimeParseException ex) {
            JOptionPane.showMessageDialog(null, "Please enter the due date in the format dd/MM/yyyy.");
            return; // exit the method
        }
                
               

               // LocalDate dueDate = LocalDate.parse(addDateTextField.getText());
                
                Task newTask = new Task(title, description, dueDate);
                // DefaultListModel<Task>  = (DefaultListModel<Task>) taskList.getModel();
                taskList.getModel();
                model.addElement(newTask);
                taskList.repaint();
                int numTasks = model.getSize();
                taskCountDisplay.setText(Integer.toString(numTasks));
                
                
              /*  try {
                    FileOutputStream fileOut = new FileOutputStream("tasks.ser");
                    ObjectOutputStream out = new ObjectOutputStream(fileOut);
                    out.writeObject(taskList);  // assuming taskList is the ArrayList<Task> that you want to save
                    out.close();
                    fileOut.close();
                    System.out.println("Task list saved to tasks.ser");
                    } catch (IOException e) {
                    e.printStackTrace();
                    }

                */
                
                
                
                
                
                
                
                
                
                addTaskFrame.dispose();
    }//GEN-LAST:event_addTaskOkButtonActionPerformed

    private void addDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addDateTextFieldActionPerformed

    private void addTitleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTitleTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTitleTextFieldActionPerformed

    private void addTaskCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTaskCancelButtonActionPerformed
        addTaskFrame.dispose();
    }//GEN-LAST:event_addTaskCancelButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
           
        int selectedIndex = taskList.getSelectedIndex();
    if (selectedIndex == -1) {
        // show error message that no task is selected
        JOptionPane.showMessageDialog(this, "Please select a task to remove.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
        
        
        taskList.getModel();
           Task selectedTask = (Task) taskList.getSelectedValue();

           model.removeElement(selectedTask);
           
            int numTasks = model.getSize();
            taskCountDisplay.setText(Integer.toString(numTasks));
            jLabel1.setVisible(false);
            jLabel2.setVisible(false);
            jLabel3.setVisible(false);
            jLabel4.setVisible(false);
            descDisplayTextArea.setText("");
            progDisplayLabel.setText("");
            titleDisplayLabel.setText("");     
            dateDisplayLabel.setText("");    
    }//GEN-LAST:event_removeButtonActionPerformed

    private void editTaskOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTaskOkButtonActionPerformed
            taskList.getModel();
            Task selectedTask = (Task) taskList.getSelectedValue();
            
            selectedTask.setTitle(editTitleTextField.getText());
            selectedTask.setDescription(editDescriptionTextArea.getText());
            
               if (editTitleTextField.getText().isEmpty()) {
                        JOptionPane.showMessageDialog(null, "Please enter a title for the task.");
                         return; // exit the method
                 }
        
             if (editDateTextField.getText().isEmpty()) {
                        JOptionPane.showMessageDialog(addTaskFrame, "Due date cannot be empty", "Error", JOptionPane.ERROR_MESSAGE);
                        return;
                   }
                
                 
             
             
                //DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                //LocalDate dueDate = LocalDate.parse(editDateTextField.getText(), formatter);
                
                 LocalDate dueDate;
               
        try {
            dueDate = LocalDate.parse(editDateTextField.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        } catch (DateTimeParseException ex) {
            JOptionPane.showMessageDialog(null, "Please enter the due date in the format dd/MM/yyyy.");
            return; // exit the method
        }
                
                
                
                
            selectedTask.setDueDate(dueDate);
            //selectedTask.setCompleted(editedTask.isDone());
            
             if (selectedTask.isDone()) {
                progDisplayLabel.setText("Completed");
          } else {
                progDisplayLabel.setText("In Progress");
            }
                         
             
             
             
             titleDisplayLabel.setText(selectedTask.getTitle());
            dateDisplayLabel.setText((selectedTask.getDueDate()).format(DateTimeFormatter.ISO_DATE) );
            descDisplayTextArea.setText(selectedTask.getDescription());
             taskList.repaint();
             
             
          /*   try {
                    FileOutputStream fileOut = new FileOutputStream("tasks.ser");
                    ObjectOutputStream out = new ObjectOutputStream(fileOut);
                    out.writeObject(taskList);  // assuming taskList is the ArrayList<Task> that you want to save
                    out.close();
                    fileOut.close();
                    System.out.println("Task list saved to tasks.ser");
                } catch (IOException e) {
                    e.printStackTrace();
                }

             
             */
             
             
             
             
             
             editTaskFrame.dispose();
    }//GEN-LAST:event_editTaskOkButtonActionPerformed

    private void editTaskCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTaskCancelButtonActionPerformed
        editTaskFrame.dispose();
    }//GEN-LAST:event_editTaskCancelButtonActionPerformed

    private void editTitleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTitleTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editTitleTextFieldActionPerformed

    private void editDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editDateTextFieldActionPerformed

    private void doneCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneCheckBoxActionPerformed
            taskList.getModel();
            Task selectedTask = (Task) taskList.getSelectedValue();
            selectedTask.setCompleted(rootPaneCheckingEnabled);
    }//GEN-LAST:event_doneCheckBoxActionPerformed

    private void notDoneCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notDoneCheckBoxActionPerformed
             taskList.getModel();
            Task selectedTask = (Task) taskList.getSelectedValue();
            selectedTask.setNotCompleted(rootPaneCheckingEnabled);
    }//GEN-LAST:event_notDoneCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Cupertino Light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });*/
    }
    
     DefaultListModel<Task> model = new DefaultListModel<>();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TopPanel;
    private javax.swing.JPanel TopPanel1;
    private javax.swing.JPanel TopPanel2;
    private javax.swing.JButton addButton;
    private javax.swing.JTextField addDateTextField;
    private javax.swing.JTextArea addDescriptionTextArea;
    private javax.swing.JButton addTaskCancelButton;
    private javax.swing.JFrame addTaskFrame;
    private javax.swing.JButton addTaskOkButton;
    private javax.swing.JTextField addTitleTextField;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JPanel bottomPanel1;
    private javax.swing.JPanel bottomPanel2;
    private javax.swing.JLabel dateDisplayLabel;
    private javax.swing.JTextArea descDisplayTextArea;
    private javax.swing.JCheckBox doneCheckBox;
    private javax.swing.JButton editButton;
    private javax.swing.JTextField editDateTextField;
    private javax.swing.JTextArea editDescriptionTextArea;
    private javax.swing.JButton editTaskCancelButton;
    private javax.swing.JFrame editTaskFrame;
    private javax.swing.JButton editTaskOkButton;
    private javax.swing.JTextField editTitleTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JCheckBox notDoneCheckBox;
    private javax.swing.JLabel progDisplayLabel;
    private javax.swing.JButton removeButton;
    private javax.swing.JLabel taskCountDisplay;
    private javax.swing.JList<Task> taskList;
    private javax.swing.JLabel taskNumTextLabel;
    private javax.swing.JLabel titleDisplayLabel;
    // End of variables declaration//GEN-END:variables
}
